feat: Проект ShareIt, Часть 3(запросы и пагинация)
rs-popov/java-shareit pull request #4
Opened 2022-09-14 07:58 UTC by rs-popov

2022-09-16 21:37 UTC, Fleaman777 requested changes

2022-09-16 21:37 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        int page = from < size ? 0 : from / size;
эту логику можно вынести в отдельный метод, который мог бы возвращать PageRequest.of(page, size)

2022-09-16 21:37 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/requests/dto/ItemRequestDto.java
> +    LocalDateTime created;
поля должны быть private

аналагично в похожих местах

2022-09-16 21:37 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +        List<ItemRequest> itemRequests = itemRequestRepository.findItemRequestsByRequestorId(requesterId);
в принципе можно не выносить в отдельную переменную, а сразу на результате от findItemRequestsByRequestorId(...) делать stream

2022-09-16 21:37 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +                        .accept(MediaType.APPLICATION_JSON))
создание контента можно было бы вынести в отдельный метод, который бы принимал dto

2022-09-16 21:37 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +        final InputBookingDto nonValidBooking = InputBookingDto.builder()
как еще вариант: 
nonValid = invalid

2022-09-16 21:37 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +                .thenReturn(BookingMapper.toBookingDto(booking));
если пустой строкой разделять код для when и для perform, 
код чуть лучше будет восприниматься

2022-09-16 21:37 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTests.java
> +        ItemInputDto createdItem = itemService.createItem(ItemMapper.toItemDto(item), ownerCreated.getId());
создание ownerCreated, bookerCreated, createdItem - можно вынести в метод с аннтоацией beforeEach

2022-09-16 21:37 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingUnitTests.java
> +        assertTrue(bookings.get(0).getEnd().isAfter(LocalDateTime.now()));
LocalDateTime.now() можно было бы вынести в локальную переменную

2022-09-16 21:37 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingUnitTests.java
> +                .thenReturn(new PageImpl<Booking>(List.of()));
еще вариант, использовать готовую пустую коллекцию, ColletctionUtil.emptyList

2022-09-16 21:37 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/ItemControllerTests.java
> +                        .accept(MediaType.APPLICATION_JSON))
здесь тоже можно убщую часть вынести в отдельный вспомогательный метод

2022-09-16 21:37 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/ItemUnitTests.java
> +public class ItemUnitTests {
не совсем понятно, к какому именно классу относится этот тест класс, лучше придерживаться общепринятого подхода: "название класса + Test" 
например ItemServiceImplTest, ItemRepositoryTest с контроллером нейминг немного другой ItemControllerIntegrationTest 

замечание относится ко всем аналагичным местам

2022-09-16 21:37 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/ItemUnitTests.java
> +    void getItemByIdWithUnknownId_shouldThrowException() {
не первый раз встречаю в работах студентов в названиях методов, нижнее подчеркивание, 
на сколько мне известно, в названиях методов оно обычно не ипользуется,

выглядит так, как-будто у вас где-то в методичках есть подобные примеры, 
угадал ?)
или просто у всех так случайно получается ?)

2022-09-17 11:12 UTC, rs-popov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        int page = from < size ? 0 : from / size;
Добавил метод getPageRequest здесь и аналогично в классах ItemServiceImpl и ItemRequestServiceImpl

2022-09-17 11:14 UTC, rs-popov commented on src/main/java/ru/practicum/shareit/requests/dto/ItemRequestDto.java
> +    LocalDateTime created;
Исправил здесь и для полей модели ItemRequest

2022-09-17 11:17 UTC, rs-popov commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +        List<ItemRequest> itemRequests = itemRequestRepository.findItemRequestsByRequestorId(requesterId);
Убрал переменную itemRequests

2022-09-17 11:21 UTC, rs-popov commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +        final InputBookingDto nonValidBooking = InputBookingDto.builder()
Исправил и в аналогичных местах

2022-09-17 11:27 UTC, rs-popov commented on src/test/java/ru/practicum/shareit/item/ItemUnitTests.java
> +    void getItemByIdWithUnknownId_shouldThrowException() {
Скорее всего случайно:) я специально добавлял подчеркивания чтобы видеть тесты с эксепшенами и забыл исправить

2022-09-17 12:52 UTC, rs-popov commented on src/test/java/ru/practicum/shareit/item/ItemControllerTests.java
> +                        .accept(MediaType.APPLICATION_JSON))
Добавил метод createContentFromItemInputDto(MockHttpServletRequestBuilder builder, ItemInputDto itemInputDto, Long id), куда вынес общую часть

2022-09-18 13:15 UTC, Fleaman777 approved these changes

2022-09-18 13:15 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +    void addBookingWithInvalidBookingShouldThrowException() throws Exception {
хорошее название метода, 
но например, я чаще встречал нейминг когда идет сначала часть с should, 
затем все остальное т.е.
shouldThrowExceptionOnPostAddBookingWithInvalidBooking

возможно это чисто вкусовщина, но выглядит и понимается - хорошо,
сейчас можешь не исправлять, это так, больше момент на будущее

2022-09-18 13:15 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/requests/ItemRequestsServiceImplTests.java
> +public class ItemRequestsServiceImplTests {
Test обычно в единственном числе - здесь он больше показывает, 
что этот класс является тестовым для ItemRequestsServiceImpl, чем класс, который содержит тесты для ItemRequestsServiceImpl
 
 тоже можешь пока не исправлять, это на будущее

2022-09-19 00:32 UTC, merged